//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCaddins.ExportManager {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class Settings1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings1 defaultInstance = ((Settings1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings1())));
        
        public static Settings1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\SCAPP01\\FollowYouColour")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public string A3PrinterDriver {
            get {
                return ((string)(this["A3PrinterDriver"]));
            }
            set {
                this["A3PrinterDriver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("R2010")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public string AcadExportVersion {
            get {
                return ((string)(this["AcadExportVersion"]));
            }
            set {
                this["AcadExportVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public bool AdobePDFMode {
            get {
                return ((bool)(this["AdobePDFMode"]));
            }
            set {
                this["AdobePDFMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Adobe PDF")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public string AdobePrinterDriver {
            get {
                return ((string)(this["AdobePrinterDriver"]));
            }
            set {
                this["AdobePrinterDriver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Temp")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public string ExportDir {
            get {
                return ((string)(this["ExportDir"]));
            }
            set {
                this["ExportDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public bool ForceDateRevision {
            get {
                return ((bool)(this["ForceDateRevision"]));
            }
            set {
                this["ForceDateRevision"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\gs\\gs9.15\\bin")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public string GSBinDirectory {
            get {
                return ((string)(this["GSBinDirectory"]));
            }
            set {
                this["GSBinDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\gs\\gs9.15\\lib")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public string GSLibDirectory {
            get {
                return ((string)(this["GSLibDirectory"]));
            }
            set {
                this["GSLibDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public bool HideTitleBlocks {
            get {
                return ((bool)(this["HideTitleBlocks"]));
            }
            set {
                this["HideTitleBlocks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\SCAPP01\\DocuWide3035 (PS)")]
        public string LargeFormatPrinterDriver {
            get {
                return ((string)(this["LargeFormatPrinterDriver"]));
            }
            set {
                this["LargeFormatPrinterDriver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("North Point")]
        public string NorthPointVisibilityParameter {
            get {
                return ((string)(this["NorthPointVisibilityParameter"]));
            }
            set {
                this["NorthPointVisibilityParameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>a0\t\t(\t841\tx 1189\tmm\t)</string>\r\n  <string>a1\t\t(\t594\tx 841\tmm\t)</string>\r\n " +
            " <string>a2\t\t(\t420\tx 594\tmm\t)</string>\r\n  <string>a3\t\t(\t297\tx 420\tmm\t)</string>\r" +
            "\n  <string>a4\t\t(\t210\tx 297\tmm\t)</string>\r\n  <string>a4 small\t(\t210\tx 297\tmm\t)</s" +
            "tring>\r\n  <string>a5\t\t(\t148\tx 210\tmm\t)</string>\r\n  <string>a6\t\t(\t105\tx 148\tmm\t)<" +
            "/string>\r\n  <string>a7\t\t(\t74\tx 105\tmm\t)</string>\r\n  <string>a8\t\t(\t52\tx 74\tmm\t)</" +
            "string>\r\n  <string>a9\t\t(\t37\tx 52\tmm\t)</string>\r\n  <string>a10\t\t(\t26\tx 37\tmm\t)</s" +
            "tring>\r\n  <string>iso b0\t\t(\t1000\tx 1414\tmm\t)</string>\r\n  <string>iso b1\t\t(\t707\tx" +
            " 1000\tmm\t)</string>\r\n  <string>iso b2\t\t(\t500\tx 707\tmm\t)</string>\r\n  <string>iso " +
            "b3\t\t(\t353\tx 500\tmm\t)</string>\r\n  <string>iso b4\t\t(\t250\tx 353\tmm\t)</string>\r\n  <s" +
            "tring>iso b5\t\t(\t176\tx 250\tmm\t)</string>\r\n  <string>iso b6\t\t(\t125\tx 176\tmm\t)</str" +
            "ing>\r\n  <string>c0\t\t(\t917\tx 1297\tmm\t)</string>\r\n  <string>c1\t\t(\t648\tx 917\tmm\t)</" +
            "string>\r\n  <string>c2\t\t(\t458\tx 648\tmm\t)</string>\r\n  <string>c3\t\t(\t324\tx 458\tmm\t)" +
            "</string>\r\n  <string>c4\t\t(\t229\tx 324\tmm\t)</string>\r\n  <string>c5\t\t(\t162\tx 229\tmm" +
            "\t)</string>\r\n  <string>c6\t\t(\t114\tx 162\tmm\t)</string>\r\n  <string>jis b0\t\t(\t1030\tx" +
            " 1456\tmm\t)</string>\r\n  <string>jis b1\t\t(\t728\tx 1030\tmm\t)</string>\r\n  <string>jis" +
            " b2\t\t(\t515\tx 728\tmm\t)</string>\r\n  <string>jis b3\t\t(\t364\tx 515\tmm\t)</string>\r\n  <" +
            "string>jis b4\t\t(\t257\tx 364\tmm\t)</string>\r\n  <string>jis b5\t\t(\t182\tx 257\tmm\t)</st" +
            "ring>\r\n  <string>jis b6\t\t(\t128\tx 182\tmm\t)</string>\r\n  <string>11x17\t  \t(\t279\tx 4" +
            "32\tmm\t)</string>\r\n  <string>ledger\t\t(\t432\tx 279\tmm\t)</string>\r\n  <string>legal\t\t" +
            "(\t216\tx 356\tmm\t)</string>\r\n  <string>letter\t\t(\t216\tx 279\tmm\t)</string>\r\n  <strin" +
            "g>letter small\t(\t216\tx 279\tmm\t)</string>\r\n  <string>arch E\t\t(\t914\tx 1219\tmm\t)</s" +
            "tring>\r\n  <string>arch D\t\t(\t610\tx 914\tmm\t)</string>\r\n  <string>arch C\t\t(\t457\tx 6" +
            "10\tmm\t)</string>\r\n  <string>arch B\t\t(\t305\tx 457\tmm\t)</string>\r\n  <string>arch A\t" +
            "\t(\t229\tx 305\tmm\t)</string>\r\n  <string>ANSI A (8.5x11in)</string>\r\n  <string>ANSI" +
            " B (11x17in)</string>\r\n  <string>ANSI C (17x22in)</string>\r\n  <string>ANSI D (22" +
            "x34in)</string>\r\n  <string>ANSI E (34x44)</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PaperSizes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PaperSizes"]));
            }
            set {
                this["PaperSizes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\SCAPP01\\DocuWide3035 (PS)")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public string PSPrinterDriver {
            get {
                return ((string)(this["PSPrinterDriver"]));
            }
            set {
                this["PSPrinterDriver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Scalebar Scale")]
        public string ScalebarScaleParameter {
            get {
                return ((string)(this["ScalebarScaleParameter"]));
            }
            set {
                this["ScalebarScaleParameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowExportLog {
            get {
                return ((bool)(this["ShowExportLog"]));
            }
            set {
                this["ShowExportLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public bool TagPDFExports {
            get {
                return ((bool)(this["TagPDFExports"]));
            }
            set {
                this["TagPDFExports"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("notepad.exe")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public string TextEditor {
            get {
                return ((string)(this["TextEditor"]));
            }
            set {
                this["TextEditor"] = value;
            }
        }
    }
}
